### ISSUE TITLE
Minecraft chat not passed into Discord

### ISSUE THREAD

**Issue by twrist** [destruc7i0n/shulker#15]
Hi,
I've been having an issue with this, where the app receives the in-game chat fine (as shown by the console log), but then never sends that message to Discord. The reverse (Discord to Minecraft) works perfectly.
The most I've been able to get out of it is this stacktrace:

```
TypeError: Cannot read property 'sendMessage' of null                                                                 
    at /home/minecraft/discordrelay/index.js:42:48
    at Layer.handle [as handle_request] (/home/minecraft/discordrelay/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/minecraft/discordrelay/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/minecraft/discordrelay/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/minecraft/discordrelay/node_modules/express/lib/router/layer.js:95:5)
    at /home/minecraft/discordrelay/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/minecraft/discordrelay/node_modules/express/lib/router/index.js:330:12)
    at next (/home/minecraft/discordrelay/node_modules/express/lib/router/index.js:271:10)
    at IncomingMessage.<anonymous> (/home/minecraft/discordrelay/index.js:24:9)
    at emitNone (events.js:67:13)
```

**Comment by SecretOnline** [comment]
Try changing `shulker.channels.get("id", channel).sendMessage(message);` (line 42) to `shulker.channels.get("name", channel).sendMessage(message);`
