### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Saamstep** [destruc7i0n/shulker#23]
```
`if (message.channel.id === shulker.channels.get(c.DISCORD_CHANNEL_ID).id) {
                                                                         ^

TypeError: Cannot read property 'id' of undefined
    at Client.<anonymous> (/app/index.js:54:74)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)`
```

An error occurred when I tried running the app on Heroku

**Comment by megaxlr** [comment]
The Channel ID you entered is wrong. make sure to enter the right channel ID.

TIP: Enable Discord Developer Mode (User settings > Appearance). Right click the channel and press "Copy ID"

**Comment by Saamstep** [comment]
ahh silly me I put the channel name not ID. This is why you should not set stuff up at 12AM D:. Thnx :D
