### ISSUE TITLE
TypeError when webhook called with chat text

### ISSUE THREAD

**Issue by KronK0321** [destruc7i0n/shulker#26]
I've got the Discord --> Minecraft functionality working. But shulker errors when it parses the latest.log

```$ npm start

> shulker@1.0.0 start /opt/shulker
> node index.js

[INFO] Bot listening on *:25501
[INFO] Recieved [17:12:16 INFO]: <Baphomet> Test from MC
TypeError: Cannot read property '1' of null
    at /opt/shulker/index.js:38:61
    at Layer.handle [as handle_request] (/opt/shulker/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/shulker/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/shulker/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/shulker/node_modules/express/lib/router/layer.js:95:5)
    at /opt/shulker/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/shulker/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/shulker/node_modules/express/lib/router/index.js:275:10)
    at IncomingMessage.<anonymous> (/opt/shulker/index.js:24:9)
    at emitNone (events.js:106:13)
```

The following was me feeding it a log line but I receive the same error when the while loop parses the latest.log as well
```
 $ echo "[17:12:16 INFO]: <Baphomet> Test from MC" |  curl -X POST -d @- http://localhost:25501/minecraft/hook
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;1&#39; of null<br> &nbsp; &nbsp;at /opt/shulker/index.js:38:61<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/shulker/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/opt/shulker/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/opt/shulker/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/shulker/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /opt/shulker/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/opt/shulker/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/opt/shulker/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/shulker/index.js:24:9)<br> &nbsp; &nbsp;at emitNone (events.js:106:13)</pre>
</body>
</html>
```

```
cat config.json
{
    "PORT": 25501,
    "DISCORD_TOKEN": "REDACTED",
    "DISCORD_CHANNEL_ID": "480132340551516160",
    "MINECRAFT_SERVER_RCON_IP": "localhost",
    "MINECRAFT_SERVER_RCON_PORT": 25575,
    "MINECRAFT_SERVER_RCON_PASSWORD": "REDACTED",
    "WEBHOOK": "/minecraft/hook",
    "REGEX_MATCH_CHAT_MC": "\\[Server thread/INFO\\]: <([^>]*)> (.*)",
    "REGEX_IGNORED_CHAT": "packets too frequently",
    "RCON_RECONNECT_DELAY": 10,
    "DEBUG": true
}
```

```
$ npm version
{ shulker: '1.0.0',
  npm: '6.4.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.3',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }
```

What have I done wrong?

**Comment by KronK0321** [comment]
Hah, nevermind, sorry. It's my "REGEX_MATCH_CHAT_MC" that needs to be updated.

``` 
"REGEX_MATCH_CHAT_MC": "\\[Async Chat Thread - #[0-9]/INFO\\]: <([^>]*)> (.*)",
```
