### ISSUE TITLE
messages from within discord crash shulker

### ISSUE THREAD

**Issue by CorQB** [destruc7i0n/shulker#35]
Messages sent from discord app crash the shulker server with:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:65535
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
error Command failed with exit code 1.

```
Interestingly, chat from my minecraft server comes through to discord perfectly; has anyone else experienced this issue? Being that there is quite a lot of configuration between shulker and the discord bot I'm not sure that I haven't configured something incorrectly, but I'm unable to find any logs to break the issue down any further.

Shulker running with yarn, and here's my config.json:

```
    "PORT": 8000,
    "USE_WEBHOOKS": true,
    "WEBHOOK_URL": "https://discordapp.com/###
    "DISCORD_TOKEN": "NTI4Nzkx#######",
    "DISCORD_CHANNEL_ID": "5287######",
    "DISCORD_MESSAGE_TEMPLATE": "`%username%`: %message%",
    "MINECRAFT_SERVER_RCON_IP": "127.0.0.1",
    "MINECRAFT_SERVER_RCON_PORT": 65535,
    "MINECRAFT_SERVER_RCON_PASSWORD": "#######",
    "MINECRAFT_TELLRAW_TEMPLATE": "[{\"color\": \"white\", \"text\": \"<%username%> %mess$
    "WEBHOOK": "/minecraft/hook",
    "REGEX_MATCH_CHAT_MC": "\\[Server thread/INFO\\]: <([^>]*)> (.*)",
    "REGEX_IGNORED_CHAT": "packets too frequently",
    "RCON_RECONNECT_DELAY": 10,
    "DEBUG": true


```

**Comment by CorQB** [comment]
Doh. I had Rcon and shulker ports mismatched - problem solved :1st_place_medal:
