### ISSUE TITLE
Error inside of bot log. (MC chat to discord doesn't work)

### ISSUE THREAD

**Issue by MultiLagio** [destruc7i0n/shulker#36]
It's similar to this issue: https://github.com/destruc7i0n/shulker/issues/15.

This is the error:
`TypeError: Cannot read property '1' of null
    at /home/lando/shulker/index.js:70:45
    at Layer.handle [as handle_request] (/home/lando/shulker/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lando/shulker/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lando/shulker/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lando/shulker/node_modules/express/lib/router/layer.js:95:5)
    at /home/lando/shulker/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/lando/shulker/node_modules/express/lib/router/index.js:335:12)
    at next (/home/lando/shulker/node_modules/express/lib/router/index.js:275:10)
    at IncomingMessage.<anonymous> (/home/lando/shulker/index.js:58:5)
    at IncomingMessage.emit (events.js:197:13)`

**Comment by MultiLagio** [comment]
I feel pretty dumb right now. It's because I'm running forge so the logs are a little bit different than vanilla minecraft.
Can somebody help me with the config to make it work with the new log style?
A chat log would look like this:
`[02:58:54] [Server thread/INFO] [minecraft/DedicatedServer]: <Bread_Man_> modular enchant room`
Right now I have this in my config:
`"REGEX_MATCH_CHAT_MC": "\\[Server thread/INFO\\] \\[minecraft/DedicatedServer\\]: <([^>]*)> (.*)",`
I get the same error. Any help would be appreciated!

**Comment by destruc7i0n** [comment]
That's very odd... The regex looks like it would work. Maybe try removing the blocks for the server thread etc? 
If that fails, I just pushed a version with some updates and support for direct log file reading, try that and tell me if it works.

**Comment by MultiLagio** [comment]
Thanks for pushing the update! Really convenient to integrate the tail script.
I also solved the issue. So...
It turns out forge, it outputs different lines to the actual console compared to the log file.
So in the console it says:
`[02:30:39] [Server thread/INFO] [minecraft/DedicatedServer]: <Luxanima> no`

But in the actual log file it instead says:
`[02:30:39] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: <Luxanima> no`

so i changed the regex expression and then it worked!
