### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by Stayingfalse** [destruc7i0n/shulker#66]
Getting error unable to authenticate with Rcon, definitely attempting to connect as can see all the connections starting and ending in the log however it's not authenticating and is giving the error message in title.

This is stopping all messages from Discord not to post to the server.

Password is correct.

**Comment by Stayingfalse** [comment]
`[INFO] Using the Discord bot to send messages
[INFO] Using configuration for local log file at "/home/mcserver/serverfiles/logs/latest.log"
[INFO] Authenticated with 85.159.211.247:25575
[ERROR] Could not send password to Rcon server!
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at checkBounds (internal/buffer.js:30:5)
    at checkInt (internal/buffer.js:37:3)
    at writeU_Int32LE (internal/buffer.js:647:3)
    at Buffer.writeInt32LE (internal/buffer.js:816:10)
    at Rcon.sendPackage (/home/mcserver/shulker/build/Rcon.js:144:14)
    at Rcon.<anonymous> (/home/mcserver/shulker/build/Rcon.js:110:61)
    at step (/home/mcserver/shulker/build/Rcon.js:33:23)
    at Object.next (/home/mcserver/shulker/build/Rcon.js:14:53)
    at /home/mcserver/shulker/build/Rcon.js:8:71
[ERROR] Could not auth with the server!
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at checkBounds (internal/buffer.js:30:5)
    at checkInt (internal/buffer.js:37:3)
    at writeU_Int32LE (internal/buffer.js:647:3)
    at Buffer.writeInt32LE (internal/buffer.js:816:10)
    at Rcon.sendPackage (/home/mcserver/shulker/build/Rcon.js:144:14)
    at Rcon.<anonymous> (/home/mcserver/shulker/build/Rcon.js:110:61)
    at step (/home/mcserver/shulker/build/Rcon.js:33:23)
    at Object.next (/home/mcserver/shulker/build/Rcon.js:14:53)
    at /home/mcserver/shulker/build/Rcon.js:8:71
[DEBUG] Sending command "/tellraw @a [{"color": "white", "text": "<cezzbb> Working really?"}]" to the server
Unexpected rcon response -1 2
[DEBUG] Received [04:24:02] [RCON Listener #2/INFO]: Thread RCON Client /85.159.211.247 started
[DEBUG] Regex could not match the string:
Received: "[04:24:02] [RCON Listener #2/INFO]: Thread RCON Client /85.159.211.247 started", Regex matches lines that start with: "\[Server thread/INFO\] \[.*\]:"
[ERROR] Could not send command!
Server sent no request in 5 seconds
[DEBUG] Rcon closed!
[DEBUG] Received [04:24:07] [RCON Client /85.159.211.247 #13/INFO]: Thread RCON Client /85.159.211.247 shutting down
[DEBUG] Regex could not match the string:
Received: "[04:24:07] [RCON Client /85.159.211.247 #13/INFO]: Thread RCON Client /85.159.211.247 shutting down", Regex matches lines that start with: "\[Server thread/INFO\] \[.*\]:"

`

**Comment by destruc7i0n** [comment]
Apologies for the delay. Could you provide what server version and/or software you were running? Not sure what is the problem here.
